# Generated by Django 4.2.16 on 2024-11-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='축제 이름')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='지역')),
                ('period', models.CharField(blank=True, max_length=255, null=True, verbose_name='기간')),
                ('nature', models.CharField(blank=True, max_length=255, null=True, verbose_name='축제 성격')),
                ('fee', models.CharField(blank=True, max_length=255, null=True, verbose_name='입장료')),
                ('info', models.TextField(blank=True, null=True, verbose_name='추가 정보')),
                ('url', models.URLField(blank=True, null=True, verbose_name='상세 페이지 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
        ),
    ]
