# Generated by Django 4.2.16 on 2024-11-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='뉴스 제목')),
                ('originallink', models.URLField(verbose_name='원본 링크')),
                ('link', models.URLField(verbose_name='네이버 뉴스 링크')),
                ('description', models.TextField(blank=True, null=True, verbose_name='뉴스 요약')),
                ('pub_date', models.DateTimeField(verbose_name='발행일')),
            ],
        ),
    ]
