# Generated by Django 4.2.16 on 2024-11-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('originallink', models.URLField()),
                ('link', models.URLField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Festival_News',
        ),
    ]
