# Generated by Django 4.2.16 on 2024-11-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals_news', '0002_festivalnews_delete_festival_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalnews',
            name='festival_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='festivalnews',
            name='title',
            field=models.CharField(),
        ),
    ]
