# Generated by Django 4.2.16 on 2024-11-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals_news', '0003_alter_festivalnews_festival_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalnews',
            name='festival_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='festivalnews',
            name='link',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='festivalnews',
            name='originallink',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='festivalnews',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
