# Generated by Django 4.2.16 on 2024-11-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals_news', '0004_alter_festivalnews_festival_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalnews',
            name='main_region',
            field=models.CharField(default='기타', max_length=255),
            preserve_default=False,
        ),
    ]
